export = [
    "!.*/**/*",
    "!.*",
    "*.map",
    ".git/",
    ".cache/",
    ".rush/",
    ".vscode/",
    "public/",
    "dist/",
    "node_modules/",
    "!src/**/*",
    "cdk.out/",
    "deploy.out/",
];